# AttentionUNet 训练配置
gpu_id: "0"
# data_dir: "/data/lzf/Code/dataset/nnUNet_raw/Dataset701_STS3D_ROI"  # Server 414
data_dir: "/home/data2/lzf/Code/dataset/nnUNet_raw/Dataset701_STS3D_ROI"  # Server 708
model_save_dir: "./weights/attention_unet"
roi_size: [96, 96, 96]
num_workers: 3
cache_rate: 1

# 训练参数
max_iterations: 3600
val_interval: 90
load_batch_size: 1
num_samples: 8
lr: 1.0e-4
