# DiNTS Retrain 配置
gpu_id: "1"
# data_dir: "/home/ta/lzf/Code/dataset/nnUNet_raw/Dataset701_STS3D_ROI"
data_dir: "/home/data2/lzf/Code/dataset/nnUNet_raw/Dataset701_STS3D_ROI"
model_save_dir: "./weights/dints_retrain_seed{seed}"
arch_save_dir: "./results/dints_arch"
# [Modify] 指定具体的架构文件路径
arch_file_path: "/home/lzf/Code/3D-Tooth-Segment/results/dints_arch_seed2027/best_arch_roi.json"
log_dir: "./logs/dints_retrain_seed{seed}"
roi_size: [96, 96, 96]
num_workers: 4
cache_rate: 1.0

# 训练参数
max_iterations: 7200
val_interval: 10
batch_size: 1
num_samples: 32

# 优化器
lr_init: 0.025
momentum: 0.9
weight_decay: 4.0e-5
